<?xml version="1.0" encoding="UTF-8"?>
<TestCase name="tst_FailCleanupTestCase">
  <Environment>
    <QtVersion>@INSERT_QT_VERSION_HERE@</QtVersion>
    <QtBuild/>
    <QTestVersion>@INSERT_QT_VERSION_HERE@</QTestVersion>
  </Environment>
  <TestFunction name="initTestCase">
    <Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
  </TestFunction>
  <TestFunction name="aTestFunction">
    <Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
  </TestFunction>
  <TestFunction name="cleanupTestCase">
    <Incident type="fail" file="qtbase/tests/auto/testlib/selftests/failcleanuptestcase/tst_failcleanuptestcase.cpp" line="0">
      <Description><![CDATA['false' returned FALSE. (Fail inside cleanupTestCase)]]></Description>
    </Incident>
    <Duration msecs="0"/>
  </TestFunction>
  <Duration msecs="0"/>
</TestCase>
